### ISSUE TITLE
Configuration setting to pr-bumper to always assume #PATCH#

### ISSUE THREAD

**Issue by psbanka** [ciena-blueplanet/pr-bumper#100]
In our workflow, we use pr-bumper to version our application which only ever sees `#PATCH#` releases unless it's time to do a release to a customer, which happens very seldom. If a developer accidentally puts a `#MINOR#` on the PR and another developer doesn't catch it, then Bad Things Happen: we have to manually revert the version, we have to clear out tags, and we have to get Special Permission from devops to clear out the build artifacts.

It would be nice if `pr-bumper` could be configured to *never* accept anything other than a `#PATCH#` — or better yet, to just always assume `#PATCH#`. Then if we need to do `#MINOR#` releases, we could just manually bump `package.json`

**Comment by job13er** [comment]
I have no problem with that configuration option being added.

Go right ahead ;)

**Comment by job13er** [comment]
I think we can actually combine this with: https://github.com/ciena-blueplanet/pr-bumper/issues/39 by introducing a feature that sets a max bump allowed. Then, in a feature branch, one could set it to `minor` and in your case, you could set it to `patch`. I'll give that a shot.

**Comment by job13er** [comment]
Resolved in #107
