### ISSUE TITLE
Update docs to specify required RO_GH_TOKEN

### ISSUE THREAD

**Issue by zakhenry** [ciena-blueplanet/pr-bumper#41]
I think this may have been a change in travis or something, but the `RO_GH_TOKEN` now needs to be added in addition to the `GITHUB_TOKEN`. Also note that they should be different and the ro token should have no claims granted as it is echoed to the travis log (!)

**Comment by job13er** [comment]
Hmm. I thought it just used anonymous access if `RO_GH_TOKEN` isn't given... I wonder if I broke that with the last change...

**Comment by job13er** [comment]
Not that I'd recommend doing that, since rate-limiting would cause intermittent failures depending on what else was being built on that travis machine.

**Comment by zakhenry** [comment]
Yea, I just realised I had the same claims granted to both tokens, and googling `RO_GH_TOKEN` returned my valid token from travis ci logs 😨 . Claims revoked and all is well now

**Comment by job13er** [comment]
whew! I will call-out that `RO_GH_TOKEN` is echo'd to the logs though. An unfortunate side-effect of secure env vars not being available on pr builds from forks.
