### ISSUE TITLE
Support suppression of reading of pr description for CHANGELOG.md content 

### ISSUE THREAD

**Issue by zakhenry** [ciena-blueplanet/pr-bumper#43]
I use https://github.com/conventional-changelog/gulp-conventional-changelog to build my changelog from commits, which conflicts with the [new pr-bumper functionality](https://github.com/ciena-blueplanet/pr-bumper/pull/32). The `pr-bumper.json` file should be configurable to suppress this feature if not desired.

**Comment by job13er** [comment]
Valid point. I'm not sure how quickly we (or I) will get to this though. In the meantime, you can explicitly install the version before the `CHANGELOG.md` stuff using `npm install -g pr-bumper@0.3.5` or you can submit a PR with the change yourself. The code where you'd want to put it is probably right around [here](https://github.com/ciena-blueplanet/pr-bumper/blob/master/lib/utils.js#L77-L115) for reading more info from `.pr-bumper.json` and [here](https://github.com/ciena-blueplanet/pr-bumper/blob/master/lib/bumper.js#L55) for actually skipping the check. 

You could probably just do a check on the config option and return a `Promise.resolve()` in the case you want to skip prepending the `CHANGELOG.md`.

**Comment by job13er** [comment]
Also, if you do opt for the PR route (pretty please), then please also update the `README.md` with some info on the new option in `.pr-bumper.json` :)
