### ISSUE TITLE
Remove hard-code path to "coverage" folder

### ISSUE THREAD

**Issue by notmessenger** [ciena-blueplanet/pr-bumper#97]
In _getCurrentCoverage()_ of __/lib/utils.js_

Should instead leverage the `ember-cli-code-coverage` configuration option values - https://github.com/kategengler/ember-cli-code-coverage#configuration

**Comment by job13er** [comment]
Maybe as an option, but `pr-bumber` is used for much more than ember projects, it should not rely on any ember specific configuration.

**Comment by job13er** [comment]
We can expose a configure option for `pr-bumper` explicitly, and/or provide an option to use `ember-cli-code-coverage` configs
